"use client";

import { useEffect, useId, useRef, useState } from "react";

/**
 * Renders a Mermaid class diagram.
 *
 * Mermaid is imported inside the effect rather than at module scope because it
 * touches the DOM on load and would break server rendering.
 *
 * The render is guarded by a `cancelled` flag. Mermaid's render is async, and
 * the design canvas re-renders on every keystroke, so without this a slow render
 * from three keystrokes ago can land after a fast one and paint a stale diagram.
 */
export function Diagram({ source, className, onRendered }: { source: string; className?: string; onRendered?: () => void }) {
  const reactId = useId();
  const id = `d${reactId.replace(/[^a-zA-Z0-9]/g, "")}`;
  const [svg, setSvg] = useState<string>("");
  const [failed, setFailed] = useState(false);
  const lastGood = useRef<string>("");
  const rendered = useRef(onRendered);
  rendered.current = onRendered;

  useEffect(() => {
    let cancelled = false;

    (async () => {
      const mermaid = (await import("mermaid")).default;

      mermaid.initialize({
        startOnLoad: false,
        securityLevel: "strict",
        theme: "base",
        fontFamily: "ui-sans-serif, system-ui, sans-serif",
        themeVariables: {
          primaryColor: "#fff",
          primaryTextColor: "#111",
          primaryBorderColor: "#999",
          lineColor: "#777",
          secondaryColor: "#fafafa",
          tertiaryColor: "#fff",
          fontSize: "13px",
          classText: "#111",
        },
      });

      try {
        const { svg: drawn } = await mermaid.render(id, source);
        if (!cancelled) {
          lastGood.current = drawn;
          setSvg(drawn);
          setFailed(false);
          // Fires after paint so a caller can animate the nodes that now exist.
          requestAnimationFrame(() => {
            if (!cancelled) rendered.current?.();
          });
        }
      } catch {
        // A half-typed class name can be unparseable for a keystroke or two.
        // Keeping the last good diagram on screen beats flashing an error.
        if (!cancelled) setFailed(lastGood.current === "");
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [source, id]);

  if (failed) {
    return (
      <div className={`diagram small ${className ?? ""}`} style={{ color: "var(--vellum-ink)", opacity: 0.6 }}>
        This design cannot be drawn yet.
      </div>
    );
  }

  return (
    <div
      className={`diagram ${className ?? ""}`}
      // Mermaid output, rendered with securityLevel strict, which strips script
      // and event handlers. The source is generated by our own emitter from
      // fields we escape, never pasted markup.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
